steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'me-central1-docker.pkg.dev/$PROJECT_ID/ashare-repo/ashare-api:${SHORT_SHA:-latest}'
      - '-t'
      - 'me-central1-docker.pkg.dev/$PROJECT_ID/ashare-repo/ashare-api:latest'
      - '-f'
      - 'Apps/Ashare.Api/Dockerfile'
      - '.'
    dir: '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'me-central1-docker.pkg.dev/$PROJECT_ID/ashare-repo/ashare-api'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ashare-api'
      - '--image'
      - 'me-central1-docker.pkg.dev/$PROJECT_ID/ashare-repo/ashare-api:latest'
      - '--region'
      - 'me-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300s'
      - '--cpu-boost'
      - '--set-env-vars'
      - 'SKIP_SEEDING=true,ASPNETCORE_ENVIRONMENT=Production'

images:
  - 'me-central1-docker.pkg.dev/$PROJECT_ID/ashare-repo/ashare-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
