name: Publish NuGet Packages

on:
  release:
    types: [created]   # يبدأ عند إنشاء Release جديد

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Pack all projects
        run: dotnet pack --configuration Release

      - name: Push only new packages
        run: |
          for pkg in $(find . -name "*.nupkg"); do
            echo "🔍 Checking $pkg"
            dotnet nuget push "$pkg" \
              --api-key ${{ secrets.NUGET_API_KEY }} \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate
          done
