# =============================================================================
# ACommerce Marketplace API - Cloud Build Configuration
# =============================================================================
#
# Usage:
#   # From repository root:
#   gcloud builds submit --config=Apps/ACommerce.Marketplace.GCP/cloudbuild.yaml .
#
#   # Or with substitutions:
#   gcloud builds submit \
#     --config=Apps/ACommerce.Marketplace.GCP/cloudbuild.yaml \
#     --substitutions=_IMAGE_TAG=1.0.0,_REGION=me-central1 \
#     .
#
# =============================================================================

# Substitution variables (can be overridden via --substitutions)
substitutions:
  _REGION: me-central1
  _REPO_NAME: acommerce
  _IMAGE_NAME: marketplace-api
  _IMAGE_TAG: latest

options:
  # Use higher CPU machine for faster builds
  machineType: E2_HIGHCPU_8
  # Enable Docker layer caching
  logging: CLOUD_LOGGING_ONLY
  # Timeout for the entire build
  timeout: 1800s

steps:
  # ==========================================================================
  # Step 1: Build the Docker image
  # ==========================================================================
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '-f'
      - 'Apps/ACommerce.Marketplace.GCP/Dockerfile'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # ==========================================================================
  # Step 2: Push to Artifact Registry
  # ==========================================================================
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}'
    waitFor:
      - 'build'

  # ==========================================================================
  # Step 3: Deploy to Cloud Run (optional - uncomment to enable)
  # ==========================================================================
  # - id: 'deploy'
  #   name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - 'acommerce-marketplace'
  #     - '--image'
  #     - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}'
  #     - '--region'
  #     - '${_REGION}'
  #     - '--platform'
  #     - 'managed'
  #     - '--allow-unauthenticated'
  #   waitFor:
  #     - 'push'

# Images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

# Build timeout
timeout: 1800s

# Tags for organizing builds in Cloud Build history
tags:
  - 'acommerce-marketplace'
  - 'api'
  - 'gcp'
