# =============================================================================
# ACommerce Marketplace API - Cloud Build Configuration
# =============================================================================
#
# Usage:
#   gcloud builds submit --project=PROJECT_ID \
#     --config=Apps/ACommerce.Marketplace.GCP/cloudbuild.yaml \
#     --region=me-central1 .
#
# =============================================================================

substitutions:
  _REGION: me-central1
  _REPO_NAME: acommerce
  _IMAGE_NAME: marketplace-api
  _IMAGE_TAG: "1.0.0"

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '-f'
      - 'Apps/ACommerce.Marketplace.GCP/Dockerfile'
      - '.'

  # Push to Artifact Registry
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

timeout: 1800s
